### ISSUE TITLE
Features planned for version 2.0 [?]

### ISSUE THREAD

**Issue by mpyw** [mpyw/co#15]
Any comments will be gratefully appreciated.

# Incompatible changes

#### v1.x (Current)

```php
$values = Co::wait([
    $ch1,
    function () { return $ch2; },
    function () { yield; return $ch3; },
    function () { return yield $ch4; },
]);
$values_will_be = [
    'Content 1',
    'Content 2',
    'Content 3',
    'Content 4',
]; 
```

#### v2.x (Future)

```php
$values = Co::wait([
    $ch1,
    function () { return $ch2; },
    function () { yield; return $ch3; },
    function () { return yield $ch4; },
]);
$values_will_be = [
    'Content 1',
    'Content 2', // or raw $ch2? Should we count non-generator functions as one level?
    $ch3,
    'Content 4',
]; 
```

**Comment by chitoku-k** [comment]
I explicitly want the result to be like:

```php
$values_will_be = [
    'Content 1',
    'Content 2',
    $ch3,
    'Content 4',
];
```

The behavior can be simply explained as each callable is called and resolved if it is yielded.

**Comment by memory-agape** [comment]
I like this result

```
$values_will_be = [
    'Content 1',
    'Content 2',
    'Content 3',
    'Content 4',
]; 
```

because, I think to use simply same result.

**Comment by mpyw** [comment]
**As of version 1.2**, this issue has been done with changing conversion rules on resolving.
We can detect **Generator Closure** (Closure that contains `yield` keywords) via reflections.

### Old

| Before | After |
|:---:|:----:|
|cURL resource|`curl_multi_getconent()` result or `CURLException`|
|Array<br>`Traversable`<br>(excluding Generator) | Array (with resolved children) or `RuntimeException`|
|Closure | Return value or `RuntimeException`|
|Generator | Return value (after all yields done) or `RuntimeException`|

### New

| Before | After |
|:---:|:----:|
|cURL resource|`curl_multi_getconent()` result or `CURLException`|
|Array|Array (with resolved children)|
|Generator Closure<br>Generator| Return value (after all yields done) or `RuntimeException`|
